[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = false

[env]
# These will be passed to cargo during build
TAURI_PLATFORM = { from_env = "TAURI_PLATFORM" }
